///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/dr01.aks
/// Generation time: Thu Oct 18 09:43:56 EDT 2018
///

/// Song 'g_song1' metadata macros
#define g_song1_address  0x300
#define g_song1_size     433
#define g_song1_end      0x4B1

/// Song 'g_song1' array declaration
extern void g_song1[g_song1_size];
