///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/dr07.aks
<<<<<<< HEAD
/// Generation time: Mon Oct  5 16:45:41 CEST 2020
=======
/// Generation time: domingo,  4 de octubre de 2020, 02:03:03 CEST
>>>>>>> eabb58ededb1a6f7b2b6edffaf79a33795de8f25
///

/// Song 'drroland' metadata macros
#define drroland_address  0x200
#define drroland_size         1623
#define drroland_end      0x856

/// Song 'drroland' array declaration
extern void drroland[drroland_size];
