///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/dr07.aks
/// Generation time: Fri Sep 25 11:11:45 CEST 2020
///

/// Song 'drroland' metadata macros
#define drroland_address  0x300
#define drroland_size     1623
#define drroland_end      0x956

/// Song 'drroland' array declaration
extern void drroland[drroland_size];
