///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/dr07.aks
<<<<<<< HEAD
/// Generation time: jueves, 17 de septiembre de 2020, 23:14:42 CEST
=======
/// Generation time: Wed Sep 16 18:15:22 CEST 2020
>>>>>>> 404d64308f818862014baed756451c21472a47f1
///

/// Song 'g_song1' metadata macros
#define g_song1_address  0x300
#define g_song1_size     1623
#define g_song1_end      0x956

/// Song 'g_song1' array declaration
extern void g_song1[g_song1_size];
