///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/end_song.aks
/// Generation time: Sat Sep 26 12:58:29 CEST 2020
///

/// Song 'end_song' metadata macros
#define end_song_address  0x40
#define end_song_size     117
#define end_song_end      0xb4

/// Song 'end_song' array declaration
extern void end_song[end_song_size];
