///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/fx02.aks
/// Generation time: sábado, 26 de septiembre de 2020, 01:19:02 CEST
///

/// Song 'fx02' metadata macros
#define fx02_address  0x959
#define fx02_size          152
#define fx02_end      0x9f0

/// Song 'fx02' array declaration
extern void fx02[fx02_size];
