///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/fx02.aks
<<<<<<< HEAD
/// Generation time: Wed Jul 15 11:49:45 CEST 2020
=======
/// Generation time: lunes,  3 de febrero de 2020, 00:29:41 CET
>>>>>>> abdf3612807cb6a09a3c62381969ca63088bbfc3
///

/// Song 'g_fx1' metadata macros
#define g_fx1_address  0x959
#define g_fx1_size     76
#define g_fx1_end      0x9a4

/// Song 'g_fx1' array declaration
extern void g_fx1[g_fx1_size];
