///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/fx02.aks
/// Generation time: Tue Oct 30 08:46:38 EDT 2018
///

/// Song 'g_fx1' metadata macros
#define g_fx1_address  0x959
#define g_fx1_size     76
#define g_fx1_end      0x9a4

/// Song 'g_fx1' array declaration
extern void g_fx1[g_fx1_size];
