///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/fx03.aks
/// Generation time: sábado, 26 de septiembre de 2020, 02:06:12 CEST
///

/// Song 'fx' metadata macros
#define fx_address  0x959
#define fx_size          141
#define fx_end      0x9e5

/// Song 'fx' array declaration
extern void fx[fx_size];
