///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/fx04.aks
/// Generation time: Sat Sep 26 14:27:03 CEST 2020
///

/// Song 'fx' metadata macros
#define fx_address  0xc0
#define fx_size     150
#define fx_end      0x155

/// Song 'fx' array declaration
extern void fx[fx_size];
