///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/fx04.aks
/// Generation time: viernes,  9 de octubre de 2020, 00:12:18 CEST
///

/// Song 'fx' metadata macros
#define fx_address  0xc5
#define fx_size          150
#define fx_end      0x15a

/// Song 'fx' array declaration
extern void fx[fx_size];
