///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/fx04.aks
/// Generation time: Sat Sep 26 12:58:28 CEST 2020
///

/// Song 'fx' metadata macros
#define fx_address  0x959
#define fx_size     150
#define fx_end      0x9ee

/// Song 'fx' array declaration
extern void fx[fx_size];
