///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/lose_song.aks
/// Generation time: domingo,  4 de octubre de 2020, 02:03:02 CEST
///

/// Song 'end_song' metadata macros
#define end_song_address  0x40
#define end_song_size          129
#define end_song_end      0xc0

/// Song 'end_song' array declaration
extern void end_song[end_song_size];
