///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/sfx.aks
/// Generation time: Fri Sep 25 11:11:44 CEST 2020
///

/// Song 'fx' metadata macros
#define fx_address  0x959
#define fx_size     55
#define fx_end      0x98f

/// Song 'fx' array declaration
extern void fx[fx_size];
