///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/win_song.aks
/// Generation time: lunes, 19 de octubre de 2020, 02:40:08 CEST
///

/// Song 'win_song' metadata macros
#define win_song_address  0x900
#define win_song_size          113
#define win_song_end      0x970

/// Song 'win_song' array declaration
extern void win_song[win_song_size];
