; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

	org 16384

Untitled_Start
Untitled_StartDisarkGenerateExternalLabel

Untitled_DisarkByteRegionStart0
	db "AT20"
Untitled_DisarkPointerRegionStart1
	dw Untitled_ArpeggioTable	; The address of the Arpeggio table.
	dw Untitled_PitchTable	; The address of the Pitch table.
	dw Untitled_InstrumentTable	; The address of the Instrument table.
	dw Untitled_EffectBlockTable	; The address of the Effect Block table.
Untitled_DisarkPointerRegionEnd1


; The addresses of each Subsong:
Untitled_DisarkPointerRegionStart2
	dw Untitled_Subsong0_Start
Untitled_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
Untitled_ArpeggioTable
Untitled_DisarkPointerRegionStart3
Untitled_DisarkPointerRegionEnd3

; Declares all the Pitches.
Untitled_PitchTable
Untitled_DisarkPointerRegionStart4
Untitled_DisarkPointerRegionEnd4

; Declares all the Instruments.
Untitled_InstrumentTable
Untitled_DisarkPointerRegionStart5
	dw Untitled_EmptyInstrument
	dw Untitled_Instrument1
	dw Untitled_Instrument2
Untitled_DisarkPointerRegionEnd5

Untitled_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
Untitled_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Untitled_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

Untitled_Instrument2
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
Untitled_EffectBlockTable
Untitled_DisarkPointerRegionStart6
	dw Untitled_EffectBlock_P4P1	; Index 0
	dw Untitled_EffectBlock_P4P2	; Index 1
	dw Untitled_EffectBlock_P4P3	; Index 2
	dw Untitled_EffectBlock_P4P4	; Index 3
	dw Untitled_EffectBlock_P4P7	; Index 4
	dw Untitled_EffectBlock_P4P0	; Index 5
Untitled_DisarkPointerRegionEnd6

Untitled_EffectBlock_P4P0
	db 4, 0
Untitled_EffectBlock_P4P1
	db 4, 1
Untitled_EffectBlock_P4P2
	db 4, 2
Untitled_EffectBlock_P4P3
	db 4, 3
Untitled_EffectBlock_P4P4
	db 4, 4
Untitled_EffectBlock_P4P7
	db 4, 7

Untitled_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Untitled_Subsong0_DisarkByteRegionStart0
Untitled_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 20	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 18	; Base note index (>=0).

Untitled_Subsong0_Linker
Untitled_Subsong0_DisarkPointerRegionStart1
; Position 0
Untitled_Subsong0_Linker_Loop
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track1
	dw Untitled_Subsong0_LinkerBlock0

; Position 1
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_LinkerBlock1

; Position 2
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track5
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_LinkerBlock1

; Position 3
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_LinkerBlock1

; Position 4
	dw Untitled_Subsong0_Track9
	dw Untitled_Subsong0_Track10
	dw Untitled_Subsong0_Track11
	dw Untitled_Subsong0_LinkerBlock1

; Position 5
	dw Untitled_Subsong0_Track12
	dw Untitled_Subsong0_Track13
	dw Untitled_Subsong0_Track14
	dw Untitled_Subsong0_LinkerBlock1

; Position 6
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track15
	dw Untitled_Subsong0_Track16
	dw Untitled_Subsong0_LinkerBlock1

; Position 7
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track17
	dw Untitled_Subsong0_Track18
	dw Untitled_Subsong0_LinkerBlock1

; Position 8
	dw Untitled_Subsong0_Track19
	dw Untitled_Subsong0_Track20
	dw Untitled_Subsong0_Track21
	dw Untitled_Subsong0_LinkerBlock1

; Position 9
	dw Untitled_Subsong0_Track22
	dw Untitled_Subsong0_Track23
	dw Untitled_Subsong0_Track24
	dw Untitled_Subsong0_LinkerBlock1

; Position 10
	dw Untitled_Subsong0_Track25
	dw Untitled_Subsong0_Track26
	dw Untitled_Subsong0_Track27
	dw Untitled_Subsong0_LinkerBlock1

; Position 11
	dw Untitled_Subsong0_Track28
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track29
	dw Untitled_Subsong0_LinkerBlock1

; Position 12
	dw Untitled_Subsong0_Track30
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track31
	dw Untitled_Subsong0_LinkerBlock1

; Position 13
	dw Untitled_Subsong0_Track32
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track33
	dw Untitled_Subsong0_LinkerBlock1

; Position 14
	dw Untitled_Subsong0_Track34
	dw Untitled_Subsong0_Track35
	dw Untitled_Subsong0_Track36
	dw Untitled_Subsong0_LinkerBlock1

; Position 15
	dw Untitled_Subsong0_Track37
	dw Untitled_Subsong0_Track38
	dw Untitled_Subsong0_Track21
	dw Untitled_Subsong0_LinkerBlock1

; Position 16
	dw Untitled_Subsong0_Track39
	dw Untitled_Subsong0_Track40
	dw Untitled_Subsong0_Track41
	dw Untitled_Subsong0_LinkerBlock1

; Position 17
	dw Untitled_Subsong0_Track42
	dw Untitled_Subsong0_Track43
	dw Untitled_Subsong0_Track24
	dw Untitled_Subsong0_LinkerBlock1

; Position 18
	dw Untitled_Subsong0_Track44
	dw Untitled_Subsong0_Track45
	dw Untitled_Subsong0_Track46
	dw Untitled_Subsong0_LinkerBlock1

; Position 19
	dw Untitled_Subsong0_Track47
	dw Untitled_Subsong0_Track48
	dw Untitled_Subsong0_Track49
	dw Untitled_Subsong0_LinkerBlock1

; Position 20
	dw Untitled_Subsong0_Track50
	dw Untitled_Subsong0_Track51
	dw Untitled_Subsong0_Track52
	dw Untitled_Subsong0_LinkerBlock1

Untitled_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Untitled_Subsong0_DisarkWordForceReference2
	dw Untitled_Subsong0_Linker_Loop

Untitled_Subsong0_LinkerBlock0
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference3
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference4
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock1
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference5
	dw Untitled_Subsong0_SpeedTrack1	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference6
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.

Untitled_Subsong0_Track0
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track1
	db 223
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 31
	db 93
	db 1	; Index to an effect block.
	db 93
	db 0	; Index to an effect block.
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 24
	db 95
	db 2	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 95
	db 2	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 90
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track2
	db 61, 7	; Waits for 8 lines.

	db 245
	db 1	; New Instrument (1).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 114
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 50
	db 117
	db 3	; Index to an effect block.
	db 53
	db 60	; Waits for 1 line.

	db 114
	db 2	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 114
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 114
	db 0	; Index to an effect block.
	db 117
	db 5	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 114
	db 0	; Index to an effect block.
	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 114
	db 1	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 50
	db 53
	db 50
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track3
	db 223
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track4
	db 231
	db 1	; New Instrument (1).
	db 4	; Index to an effect block.
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track5
	db 221
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 95
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 95
	db 2	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 31
	db 93
	db 1	; Index to an effect block.
	db 93
	db 0	; Index to an effect block.
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 90
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track6
	db 167
	db 1	; New Instrument (1).
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 39
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track7
	db 159
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 90
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track8
	db 61, 43	; Waits for 44 lines.

	db 152
	db 2	; New Instrument (2).
	db 90
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track9
	db 228
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 61, 10	; Waits for 11 lines.

	db 27
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 34
	db 36
	db 102
	db 2	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track10
	db 164
	db 2	; New Instrument (2).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 31
	db 97
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 98
	db 0	; Index to an effect block.
	db 34
	db 34
	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 38
	db 29
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track11
	db 152
	db 2	; New Instrument (2).
	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track12
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 164
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 36
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 34
	db 36
	db 102
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 107
	db 0	; Index to an effect block.
	db 61, 7	; Waits for 8 lines.

	db 36
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track13
	db 164
	db 2	; New Instrument (2).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 31
	db 97
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 98
	db 0	; Index to an effect block.
	db 34
	db 60	; Waits for 1 line.

	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 33
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track14
	db 140
	db 2	; New Instrument (2).
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 19
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track15
	db 159
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 95
	db 2	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 31
	db 93
	db 1	; Index to an effect block.
	db 93
	db 0	; Index to an effect block.
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 96
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 31
	db 93
	db 1	; Index to an effect block.
	db 93
	db 0	; Index to an effect block.
	db 95
	db 1	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 90
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track16
	db 135
	db 2	; New Instrument (2).
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 19
	db 19
	db 7
	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 7
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 19
	db 7
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 19
	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 19
	db 7
	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 7
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 90
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track17
	db 159
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 33
	db 34
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 31
	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 60	; Waits for 1 line.

	db 33
	db 34
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 90
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track18
	db 135
	db 2	; New Instrument (2).
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 19
	db 19
	db 7
	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 7
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 19
	db 7
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 19
	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 19
	db 7
	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 19
	db 7
	db 7
	db 19
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track19
	db 228
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 102
	db 2	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 26
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 24
	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 31
	db 60	; Waits for 1 line.

	db 36
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 24
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track20
	db 164
	db 2	; New Instrument (2).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 31
	db 97
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 98
	db 0	; Index to an effect block.
	db 34
	db 60	; Waits for 1 line.

	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 38
	db 29
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track21
	db 140
	db 2	; New Instrument (2).
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track22
	db 164
	db 1	; New Instrument (1).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 41
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 31
	db 38
	db 43
	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 34
	db 60	; Waits for 1 line.

	db 36
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track23
	db 164
	db 2	; New Instrument (2).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 31
	db 33
	db 60	; Waits for 1 line.

	db 34
	db 34
	db 34
	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 33
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track24
	db 140
	db 2	; New Instrument (2).
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track25
	db 166
	db 1	; New Instrument (1).
	db 61, 22	; Waits for 23 lines.

	db 19
	db 60	; Waits for 1 line.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track26
	db 159
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track27
	db 135
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track28
	db 61, 23	; Waits for 24 lines.

	db 155
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 41
	db 41
	db 41
	db 60	; Waits for 1 line.

	db 41
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 41
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 107
	db 2	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 43
	db 43
	db 43
	db 60	; Waits for 1 line.

	db 43
	db 43
	db 43
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track29
	db 152
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 24
	db 24
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 24
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 60	; Waits for 1 line.

	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 60	; Waits for 1 line.

	db 27
	db 27
	db 27
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track30
	db 171
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 46
	db 43
	db 46
	db 60	; Waits for 1 line.

	db 46
	db 43
	db 60	; Waits for 1 line.

	db 46
	db 46
	db 46
	db 43
	db 60	; Waits for 1 line.

	db 43
	db 46
	db 46
	db 60	; Waits for 1 line.

	db 46
	db 43
	db 60	; Waits for 1 line.

	db 43
	db 43
	db 43
	db 50
	db 60	; Waits for 1 line.

	db 50
	db 50
	db 50
	db 60	; Waits for 1 line.

	db 50
	db 50
	db 60	; Waits for 1 line.

	db 50
	db 50
	db 53
	db 53
	db 60	; Waits for 1 line.

	db 53
	db 53
	db 53
	db 50
	db 50
	db 50
	db 60	; Waits for 1 line.

	db 50
	db 50
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track31
	db 152
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 24
	db 24
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 24
	db 24
	db 24
	db 24
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 24
	db 27
	db 60	; Waits for 1 line.

	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 60	; Waits for 1 line.

	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 27
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track32
	db 231
	db 1	; New Instrument (1).
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 95
	db 0	; Index to an effect block.
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 55
	db 60	; Waits for 1 line.

	db 48
	db 34
	db 60	; Waits for 1 line.

	db 38
	db 33
	db 60	; Waits for 1 line.

	db 38
	db 34
	db 60	; Waits for 1 line.

	db 48
	db 55
	db 60	; Waits for 1 line.

	db 48
	db 34
	db 60	; Waits for 1 line.

	db 38
	db 31
	db 60	; Waits for 1 line.

	db 34
	db 38
	db 60	; Waits for 1 line.

	db 34
	db 55
	db 60	; Waits for 1 line.

	db 48
	db 34
	db 60	; Waits for 1 line.

	db 38
	db 33
	db 60	; Waits for 1 line.

	db 38
	db 34
	db 60	; Waits for 1 line.

	db 48
	db 55
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track33
	db 135
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 7
	db 60	; Waits for 1 line.

	db 17
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 17
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 17
	db 24
	db 90
	db 1	; Index to an effect block.
	db 71
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 7
	db 60	; Waits for 1 line.

	db 17
	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 29
	db 95
	db 1	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 90
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track34
	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 34
	db 38
	db 60	; Waits for 1 line.

	db 34
	db 55
	db 60	; Waits for 1 line.

	db 48
	db 34
	db 60	; Waits for 1 line.

	db 38
	db 33
	db 60	; Waits for 1 line.

	db 38
	db 34
	db 60	; Waits for 1 line.

	db 48
	db 55
	db 60	; Waits for 1 line.

	db 48
	db 34
	db 60	; Waits for 1 line.

	db 38
	db 103
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 95
	db 0	; Index to an effect block.
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 55
	db 60	; Waits for 1 line.

	db 48
	db 34
	db 60	; Waits for 1 line.

	db 38
	db 33
	db 38
	db 33
	db 34
	db 38
	db 34
	db 55
	db 48
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track35
	db 211
	db 2	; New Instrument (2).
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 19
	db 60	; Waits for 1 line.

	db 19
	db 19
	db 60	; Waits for 1 line.

	db 19
	db 19
	db 19
	db 60	; Waits for 1 line.

	db 29
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 29
	db 60	; Waits for 1 line.

	db 29
	db 29
	db 60	; Waits for 1 line.

	db 29
	db 36
	db 102
	db 3	; Index to an effect block.
	db 105
	db 1	; Index to an effect block.
	db 19
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 19
	db 60	; Waits for 1 line.

	db 19
	db 19
	db 60	; Waits for 1 line.

	db 19
	db 19
	db 19
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track36
	db 135
	db 2	; New Instrument (2).
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 60	; Waits for 1 line.

	db 7
	db 7
	db 7
	db 7
	db 17
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 17
	db 17
	db 17
	db 17
	db 60	; Waits for 1 line.

	db 17
	db 24
	db 90
	db 1	; Index to an effect block.
	db 93
	db 0	; Index to an effect block.
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 7
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 22
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track37
	db 164
	db 1	; New Instrument (1).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 34
	db 60	; Waits for 1 line.

	db 36
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 34
	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 34
	db 60	; Waits for 1 line.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 29
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 19
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track38
	db 228
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 31
	db 97
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 98
	db 0	; Index to an effect block.
	db 34
	db 60	; Waits for 1 line.

	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 38
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track39
	db 164
	db 1	; New Instrument (1).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 34
	db 60	; Waits for 1 line.

	db 43
	db 43
	db 60	; Waits for 1 line.

	db 34
	db 34
	db 41
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 34
	db 60	; Waits for 1 line.

	db 36
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 26
	db 88
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 98
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track40
	db 164
	db 2	; New Instrument (2).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 31
	db 33
	db 60	; Waits for 1 line.

	db 34
	db 34
	db 34
	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 90
	db 0	; Index to an effect block.
	db 88
	db 1	; Index to an effect block.
	db 86
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track41
	db 140
	db 2	; New Instrument (2).
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 12
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 60	; Waits for 1 line.

	db 17
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track42
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 36
	db 36
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 36
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 41
	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 36
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 36
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 34
	db 36
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track43
	db 164
	db 2	; New Instrument (2).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 31
	db 33
	db 60	; Waits for 1 line.

	db 34
	db 34
	db 34
	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 38
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track44
	db 164
	db 1	; New Instrument (1).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 31
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 61, 12	; Waits for 13 lines.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track45
	db 164
	db 2	; New Instrument (2).
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 33
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 60	; Waits for 1 line.

	db 36
	db 102
	db 1	; Index to an effect block.
	db 107
	db 0	; Index to an effect block.
	db 36
	db 36
	db 34
	db 36
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 31
	db 93
	db 1	; Index to an effect block.
	db 100
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 31
	db 29
	db 33
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track46
	db 143
	db 2	; New Instrument (2).
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 10
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 17
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track47
	db 152
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 31
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 34
	db 60	; Waits for 1 line.

	db 34
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 41
	db 43
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 34
	db 60	; Waits for 1 line.

	db 41
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 34
	db 60	; Waits for 1 line.

	db 41
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track48
	db 178
	db 2	; New Instrument (2).
	db 61, 22	; Waits for 23 lines.

	db 53
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track49
	db 159
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 38
	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 31
	db 93
	db 1	; Index to an effect block.
	db 93
	db 0	; Index to an effect block.
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 24
	db 95
	db 2	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 95
	db 2	; Index to an effect block.
	db 88
	db 0	; Index to an effect block.
	db 90
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track50
	db 162
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 31
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 34
	db 60	; Waits for 1 line.

	db 34
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 41
	db 43
	db 34
	db 60	; Waits for 1 line.

	db 31
	db 34
	db 60	; Waits for 1 line.

	db 41
	db 43
	db 60	; Waits for 1 line.

	db 41
	db 34
	db 60	; Waits for 1 line.

	db 41
	db 98
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 27
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track51
	db 178
	db 2	; New Instrument (2).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 46
	db 50
	db 60	; Waits for 1 line.

	db 46
	db 61, 7	; Waits for 8 lines.

	db 46
	db 48
	db 60	; Waits for 1 line.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 110
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 109
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 53
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 107
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track52
	db 223
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 31
	db 31
	db 31
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 31
	db 31
	db 60	; Waits for 1 line.

	db 31
	db 31
	db 29
	db 95
	db 1	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 93
	db 1	; Index to an effect block.
	db 95
	db 3	; Index to an effect block.
	db 95
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Untitled_Subsong0_SpeedTrack0
	db 18	; Value: 9.
	db 253	; Wait for 127 lines.
Untitled_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
Untitled_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Untitled_Subsong0_DisarkByteRegionEnd0
