; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

classics_Start
classics_StartDisarkGenerateExternalLabel

classics_DisarkByteRegionStart0
	db "AT20"
classics_DisarkPointerRegionStart1
	dw classics_ArpeggioTable	; The address of the Arpeggio table.
	dw classics_PitchTable	; The address of the Pitch table.
	dw classics_InstrumentTable	; The address of the Instrument table.
	dw classics_EffectBlockTable	; The address of the Effect Block table.
classics_DisarkPointerRegionEnd1


; The addresses of each Subsong:
classics_DisarkPointerRegionStart2
	dw classics_Subsong0_Start
	dw classics_Subsong1_Start
	dw classics_Subsong2_Start
	dw classics_Subsong3_Start
	dw classics_Subsong4_Start
	dw classics_Subsong5_Start
	dw classics_Subsong6_Start
classics_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
classics_ArpeggioTable
classics_DisarkPointerRegionStart3
classics_DisarkPointerRegionEnd3

; Declares all the Pitches.
classics_PitchTable
classics_DisarkPointerRegionStart4
classics_DisarkPointerRegionEnd4

; Declares all the Instruments.
classics_InstrumentTable
classics_DisarkPointerRegionStart5
	dw classics_EmptyInstrument
	dw classics_Instrument1
	dw classics_Instrument2
classics_DisarkPointerRegionEnd5

classics_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
classics_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

classics_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

classics_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
classics_EffectBlockTable
classics_DisarkPointerRegionStart6
	dw classics_EffectBlock_P4P0	; Index 0
	dw classics_EffectBlock_P4P1	; Index 1
	dw classics_EffectBlock_P4P2	; Index 2
classics_DisarkPointerRegionEnd6

classics_EffectBlock_P4P0
	db 4, 0
classics_EffectBlock_P4P1
	db 4, 1
classics_EffectBlock_P4P2
	db 4, 2

classics_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
classics_Subsong0_DisarkByteRegionStart0
classics_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 7	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 27	; Base note index (>=0).

classics_Subsong0_Linker
classics_Subsong0_DisarkPointerRegionStart1
; Position 0
classics_Subsong0_Linker_Loop
	dw classics_Subsong0_Track0
	dw classics_Subsong0_Track1
	dw classics_Subsong0_Track2
	dw classics_Subsong0_LinkerBlock0

; Position 1
	dw classics_Subsong0_Track3
	dw classics_Subsong0_Track4
	dw classics_Subsong0_Track2
	dw classics_Subsong0_LinkerBlock1

; Position 2
	dw classics_Subsong0_Track5
	dw classics_Subsong0_Track6
	dw classics_Subsong0_Track2
	dw classics_Subsong0_LinkerBlock1

; Position 3
	dw classics_Subsong0_Track7
	dw classics_Subsong0_Track8
	dw classics_Subsong0_Track2
	dw classics_Subsong0_LinkerBlock1

; Position 4
	dw classics_Subsong0_Track9
	dw classics_Subsong0_Track10
	dw classics_Subsong0_Track2
	dw classics_Subsong0_LinkerBlock1

; Position 5
	dw classics_Subsong0_Track11
	dw classics_Subsong0_Track12
	dw classics_Subsong0_Track2
	dw classics_Subsong0_LinkerBlock1

; Position 6
	dw classics_Subsong0_Track13
	dw classics_Subsong0_Track14
	dw classics_Subsong0_Track2
	dw classics_Subsong0_LinkerBlock1

; Position 7
	dw classics_Subsong0_Track11
	dw classics_Subsong0_Track15
	dw classics_Subsong0_Track2
	dw classics_Subsong0_LinkerBlock1

classics_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
classics_Subsong0_DisarkWordForceReference2
	dw classics_Subsong0_Linker_Loop

classics_Subsong0_LinkerBlock0
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong0_DisarkWordForceReference3
	dw classics_Subsong0_SpeedTrack0	; SpeedTrack address.
classics_Subsong0_DisarkWordForceReference4
	dw classics_Subsong0_EventTrack0	; EventTrack address.
classics_Subsong0_LinkerBlock1
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong0_DisarkWordForceReference5
	dw classics_Subsong0_SpeedTrack1	; SpeedTrack address.
classics_Subsong0_DisarkWordForceReference6
	dw classics_Subsong0_EventTrack0	; EventTrack address.

classics_Subsong0_Track0
	db 237
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 60	; Waits for 1 line.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track1
	db 61, 5	; Waits for 6 lines.

	db 230
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 61, 10	; Waits for 11 lines.

	db 25
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 25
	db 60	; Waits for 1 line.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 60	; Waits for 1 line.

	db 21
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track2
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track3
	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track4
	db 61, 5	; Waits for 6 lines.

	db 166
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 61, 10	; Waits for 11 lines.

	db 35
	db 61, 10	; Waits for 11 lines.

	db 33
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track5
	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 28
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track6
	db 61, 5	; Waits for 6 lines.

	db 159
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 60	; Waits for 1 line.

	db 28
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 21
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track7
	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track8
	db 61, 23	; Waits for 24 lines.

	db 159
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 21
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 26
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track9
	db 170
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track10
	db 61, 5	; Waits for 6 lines.

	db 166
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 34
	db 61, 10	; Waits for 11 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 34
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track11
	db 170
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 60	; Waits for 1 line.

	db 47
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track12
	db 61, 11	; Waits for 12 lines.

	db 162
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 60	; Waits for 1 line.

	db 18
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 18
	db 60	; Waits for 1 line.

	db 23
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track13
	db 170
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 25
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track14
	db 61, 5	; Waits for 6 lines.

	db 158
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 60	; Waits for 1 line.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 60	; Waits for 1 line.

	db 37
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 18
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 16
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 16
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 16
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 13
	db 61, 127	; Waits for 128 lines.


classics_Subsong0_Track15
	db 61, 5	; Waits for 6 lines.

	db 166
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 60	; Waits for 1 line.

	db 18
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 18
	db 60	; Waits for 1 line.

	db 23
	db 61, 127	; Waits for 128 lines.


; The speed tracks
classics_Subsong0_SpeedTrack0
	db 8	; Value: 4.
	db 253	; Wait for 127 lines.
classics_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
classics_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

classics_Subsong0_DisarkByteRegionEnd0
; Subsong 1
; ----------------------
classics_Subsong1_DisarkByteRegionStart0
classics_Subsong1_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 4	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 29	; Base note index (>=0).

classics_Subsong1_Linker
classics_Subsong1_DisarkPointerRegionStart1
; Position 0
classics_Subsong1_Linker_Loop
	dw classics_Subsong1_Track0
	dw classics_Subsong1_Track1
	dw classics_Subsong1_Track2
	dw classics_Subsong1_LinkerBlock0

; Position 1
	dw classics_Subsong1_Track3
	dw classics_Subsong1_Track4
	dw classics_Subsong1_Track2
	dw classics_Subsong1_LinkerBlock0

; Position 2
	dw classics_Subsong1_Track5
	dw classics_Subsong1_Track6
	dw classics_Subsong1_Track2
	dw classics_Subsong1_LinkerBlock0

; Position 3
	dw classics_Subsong1_Track7
	dw classics_Subsong1_Track8
	dw classics_Subsong1_Track2
	dw classics_Subsong1_LinkerBlock0

; Position 4
	dw classics_Subsong1_Track9
	dw classics_Subsong1_Track10
	dw classics_Subsong1_Track2
	dw classics_Subsong1_LinkerBlock0

classics_Subsong1_DisarkPointerRegionEnd1
	dw 0	; Loop.
classics_Subsong1_DisarkWordForceReference2
	dw classics_Subsong1_Linker_Loop

classics_Subsong1_LinkerBlock0
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong1_DisarkWordForceReference3
	dw classics_Subsong1_SpeedTrack0	; SpeedTrack address.
classics_Subsong1_DisarkWordForceReference4
	dw classics_Subsong1_EventTrack0	; EventTrack address.

classics_Subsong1_Track0
	db 237
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 43
	db 42
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track1
	db 61, 5	; Waits for 6 lines.

	db 218
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 28
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track2
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track3
	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 43
	db 42
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track4
	db 149
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track5
	db 168
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track6
	db 61, 5	; Waits for 6 lines.

	db 137
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 60	; Waits for 1 line.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 60	; Waits for 1 line.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 60	; Waits for 1 line.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 60	; Waits for 1 line.

	db 28
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track7
	db 166
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 44
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 45
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track8
	db 156
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 37
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track9
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 52
	db 61, 6	; Waits for 7 lines.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 47
	db 49
	db 50
	db 52
	db 54
	db 55
	db 61, 127	; Waits for 128 lines.


classics_Subsong1_Track10
	db 156
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 60	; Waits for 1 line.

	db 40
	db 61, 10	; Waits for 11 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


; The speed tracks
classics_Subsong1_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
classics_Subsong1_EventTrack0
	db 255	; Wait for 128 lines.

classics_Subsong1_DisarkByteRegionEnd0
; Subsong 2
; ----------------------
classics_Subsong2_DisarkByteRegionStart0
classics_Subsong2_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 3	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 26	; Base note index (>=0).

classics_Subsong2_Linker
classics_Subsong2_DisarkPointerRegionStart1
; Position 0
classics_Subsong2_Linker_Loop
	dw classics_Subsong2_Track0
	dw classics_Subsong2_Track1
	dw classics_Subsong2_Track2
	dw classics_Subsong2_LinkerBlock0

; Position 1
	dw classics_Subsong2_Track3
	dw classics_Subsong2_Track4
	dw classics_Subsong2_Track2
	dw classics_Subsong2_LinkerBlock0

; Position 2
	dw classics_Subsong2_Track5
	dw classics_Subsong2_Track6
	dw classics_Subsong2_Track2
	dw classics_Subsong2_LinkerBlock0

; Position 3
	dw classics_Subsong2_Track7
	dw classics_Subsong2_Track8
	dw classics_Subsong2_Track2
	dw classics_Subsong2_LinkerBlock0

classics_Subsong2_DisarkPointerRegionEnd1
	dw 0	; Loop.
classics_Subsong2_DisarkWordForceReference2
	dw classics_Subsong2_Linker_Loop

classics_Subsong2_LinkerBlock0
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong2_DisarkWordForceReference3
	dw classics_Subsong2_SpeedTrack0	; SpeedTrack address.
classics_Subsong2_DisarkWordForceReference4
	dw classics_Subsong2_EventTrack0	; EventTrack address.

classics_Subsong2_Track0
	db 232
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 41
	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 43
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 41
	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


classics_Subsong2_Track1
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 216
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 61, 127	; Waits for 128 lines.


classics_Subsong2_Track2
	db 61, 127	; Waits for 128 lines.


classics_Subsong2_Track3
	db 169
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 48
	db 60	; Waits for 1 line.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 47
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 36
	db 61, 127	; Waits for 128 lines.


classics_Subsong2_Track4
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 152
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 60	; Waits for 1 line.

	db 24
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 12
	db 61, 127	; Waits for 128 lines.


classics_Subsong2_Track5
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 180
	db 1	; New Instrument (1).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 48
	db 60	; Waits for 1 line.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 48
	db 60	; Waits for 1 line.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 48
	db 60	; Waits for 1 line.

	db 53
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 61, 127	; Waits for 128 lines.


classics_Subsong2_Track6
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 152
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 26
	db 61, 127	; Waits for 128 lines.


classics_Subsong2_Track7
	db 60	; Waits for 1 line.

	db 176
	db 1	; New Instrument (1).
	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 48
	db 60	; Waits for 1 line.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 48
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 53
	db 60	; Waits for 1 line.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 48
	db 60	; Waits for 1 line.

	db 43
	db 48
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 60	; Waits for 1 line.

	db 36
	db 61, 127	; Waits for 128 lines.


classics_Subsong2_Track8
	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 60	; Waits for 1 line.

	db 24
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 61, 127	; Waits for 128 lines.


; The speed tracks
classics_Subsong2_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
classics_Subsong2_EventTrack0
	db 255	; Wait for 128 lines.

classics_Subsong2_DisarkByteRegionEnd0
; Subsong 3
; ----------------------
classics_Subsong3_DisarkByteRegionStart0
classics_Subsong3_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 4	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 27	; Base note index (>=0).

classics_Subsong3_Linker
classics_Subsong3_DisarkPointerRegionStart1
; Position 0
classics_Subsong3_Linker_Loop
	dw classics_Subsong3_Track0
	dw classics_Subsong3_Track1
	dw classics_Subsong3_Track2
	dw classics_Subsong3_LinkerBlock0

; Position 1
	dw classics_Subsong3_Track3
	dw classics_Subsong3_Track4
	dw classics_Subsong3_Track2
	dw classics_Subsong3_LinkerBlock0

; Position 2
	dw classics_Subsong3_Track5
	dw classics_Subsong3_Track6
	dw classics_Subsong3_Track2
	dw classics_Subsong3_LinkerBlock0

; Position 3
	dw classics_Subsong3_Track7
	dw classics_Subsong3_Track8
	dw classics_Subsong3_Track2
	dw classics_Subsong3_LinkerBlock0

; Position 4
	dw classics_Subsong3_Track9
	dw classics_Subsong3_Track10
	dw classics_Subsong3_Track2
	dw classics_Subsong3_LinkerBlock0

classics_Subsong3_DisarkPointerRegionEnd1
	dw 0	; Loop.
classics_Subsong3_DisarkWordForceReference2
	dw classics_Subsong3_Linker_Loop

classics_Subsong3_LinkerBlock0
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong3_DisarkWordForceReference3
	dw classics_Subsong3_SpeedTrack0	; SpeedTrack address.
classics_Subsong3_DisarkWordForceReference4
	dw classics_Subsong3_EventTrack0	; EventTrack address.

classics_Subsong3_Track0
	db 230
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 52
	db 50
	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 45
	db 43
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 49
	db 47
	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 50
	db 45
	db 42
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 43
	db 40
	db 38
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track1
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 211
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track2
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track3
	db 166
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 45
	db 43
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 52
	db 50
	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 55
	db 52
	db 49
	db 50
	db 49
	db 48
	db 45
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track4
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 161
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 33
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 28
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 30
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track5
	db 170
	db 1	; New Instrument (1).
	db 38
	db 38
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 52
	db 50
	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 45
	db 43
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 42
	db 43
	db 45
	db 47
	db 48
	db 49
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track6
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 147
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 23
	db 60	; Waits for 1 line.

	db 24
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 22
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 35
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track7
	db 171
	db 1	; New Instrument (1).
	db 43
	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 55
	db 55
	db 55
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 40
	db 40
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 36
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track8
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 140
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 26
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 19
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 60	; Waits for 1 line.

	db 24
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track9
	db 183
	db 1	; New Instrument (1).
	db 55
	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 53
	db 52
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 55
	db 55
	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 43
	db 53
	db 52
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 43
	db 43
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 52
	db 55
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 61, 127	; Waits for 128 lines.


classics_Subsong3_Track10
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 159
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 12
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 24
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 24
	db 61, 127	; Waits for 128 lines.


; The speed tracks
classics_Subsong3_SpeedTrack0
	db 22	; Value: 11.
	db 253	; Wait for 127 lines.

; The event tracks
classics_Subsong3_EventTrack0
	db 255	; Wait for 128 lines.

classics_Subsong3_DisarkByteRegionEnd0
; Subsong 4
; ----------------------
classics_Subsong4_DisarkByteRegionStart0
classics_Subsong4_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 1	; Loop start index (>=0).
	db 1	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 15	; Base note index (>=0).

classics_Subsong4_Linker
classics_Subsong4_DisarkPointerRegionStart1
; Position 0
	dw classics_Subsong4_Track0
	dw classics_Subsong4_Track1
	dw classics_Subsong4_Track2
	dw classics_Subsong4_LinkerBlock0

; Position 1
classics_Subsong4_Linker_Loop
	dw classics_Subsong4_Track2
	dw classics_Subsong4_Track2
	dw classics_Subsong4_Track2
	dw classics_Subsong4_LinkerBlock1

classics_Subsong4_DisarkPointerRegionEnd1
	dw 0	; Loop.
classics_Subsong4_DisarkWordForceReference2
	dw classics_Subsong4_Linker_Loop

classics_Subsong4_LinkerBlock0
	db 26	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong4_DisarkWordForceReference3
	dw classics_Subsong4_SpeedTrack0	; SpeedTrack address.
classics_Subsong4_DisarkWordForceReference4
	dw classics_Subsong4_EventTrack0	; EventTrack address.
classics_Subsong4_LinkerBlock1
	db 1	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong4_DisarkWordForceReference5
	dw classics_Subsong4_SpeedTrack0	; SpeedTrack address.
classics_Subsong4_DisarkWordForceReference6
	dw classics_Subsong4_EventTrack0	; EventTrack address.

classics_Subsong4_Track0
	db 225
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 55
	db 61, 127	; Waits for 128 lines.


classics_Subsong4_Track1
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 225
	db 2	; New Instrument (2).
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 61, 127	; Waits for 128 lines.


classics_Subsong4_Track2
	db 61, 127	; Waits for 128 lines.


; The speed tracks
classics_Subsong4_SpeedTrack0
	db 8	; Value: 4.
	db 253	; Wait for 127 lines.

; The event tracks
classics_Subsong4_EventTrack0
	db 255	; Wait for 128 lines.

classics_Subsong4_DisarkByteRegionEnd0
; Subsong 5
; ----------------------
classics_Subsong5_DisarkByteRegionStart0
classics_Subsong5_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 1	; Loop start index (>=0).
	db 1	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 20	; Base note index (>=0).

classics_Subsong5_Linker
classics_Subsong5_DisarkPointerRegionStart1
; Position 0
	dw classics_Subsong5_Track0
	dw classics_Subsong5_Track1
	dw classics_Subsong5_Track2
	dw classics_Subsong5_LinkerBlock0

; Position 1
classics_Subsong5_Linker_Loop
	dw classics_Subsong5_Track2
	dw classics_Subsong5_Track2
	dw classics_Subsong5_Track2
	dw classics_Subsong5_LinkerBlock1

classics_Subsong5_DisarkPointerRegionEnd1
	dw 0	; Loop.
classics_Subsong5_DisarkWordForceReference2
	dw classics_Subsong5_Linker_Loop

classics_Subsong5_LinkerBlock0
	db 26	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong5_DisarkWordForceReference3
	dw classics_Subsong5_SpeedTrack0	; SpeedTrack address.
classics_Subsong5_DisarkWordForceReference4
	dw classics_Subsong5_EventTrack0	; EventTrack address.
classics_Subsong5_LinkerBlock1
	db 1	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong5_DisarkWordForceReference5
	dw classics_Subsong5_SpeedTrack0	; SpeedTrack address.
classics_Subsong5_DisarkWordForceReference6
	dw classics_Subsong5_EventTrack0	; EventTrack address.

classics_Subsong5_Track0
	db 247
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 55
	db 60	; Waits for 1 line.

	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 61, 127	; Waits for 128 lines.


classics_Subsong5_Track1
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 220
	db 2	; New Instrument (2).
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 61, 127	; Waits for 128 lines.


classics_Subsong5_Track2
	db 61, 127	; Waits for 128 lines.


; The speed tracks
classics_Subsong5_SpeedTrack0
	db 8	; Value: 4.
	db 253	; Wait for 127 lines.

; The event tracks
classics_Subsong5_EventTrack0
	db 255	; Wait for 128 lines.

classics_Subsong5_DisarkByteRegionEnd0
; Subsong 6
; ----------------------
classics_Subsong6_DisarkByteRegionStart0
classics_Subsong6_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 0	; Base note index (>=0).

classics_Subsong6_Linker
classics_Subsong6_DisarkPointerRegionStart1
; Position 0
classics_Subsong6_Linker_Loop
	dw classics_Subsong6_Track0
	dw classics_Subsong6_Track0
	dw classics_Subsong6_Track0
	dw classics_Subsong6_LinkerBlock0

classics_Subsong6_DisarkPointerRegionEnd1
	dw 0	; Loop.
classics_Subsong6_DisarkWordForceReference2
	dw classics_Subsong6_Linker_Loop

classics_Subsong6_LinkerBlock0
	db 1	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
classics_Subsong6_DisarkWordForceReference3
	dw classics_Subsong6_SpeedTrack0	; SpeedTrack address.
classics_Subsong6_DisarkWordForceReference4
	dw classics_Subsong6_EventTrack0	; EventTrack address.

classics_Subsong6_Track0
	db 61, 127	; Waits for 128 lines.


; The speed tracks
classics_Subsong6_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
classics_Subsong6_EventTrack0
	db 255	; Wait for 128 lines.

classics_Subsong6_DisarkByteRegionEnd0
