; Fever Remix, AKG format, v1.0.

; Generated by Arkos Tracker 2.

FeverRemix_Start
FeverRemix_StartDisarkGenerateExternalLabel

FeverRemix_DisarkByteRegionStart0
	db "AT20"
FeverRemix_DisarkPointerRegionStart1
	dw FeverRemix_ArpeggioTable	; The address of the Arpeggio table.
	dw FeverRemix_PitchTable	; The address of the Pitch table.
	dw FeverRemix_InstrumentTable	; The address of the Instrument table.
	dw FeverRemix_EffectBlockTable	; The address of the Effect Block table.
FeverRemix_DisarkPointerRegionEnd1


; The addresses of each Subsong:
FeverRemix_DisarkPointerRegionStart2
	dw FeverRemix_Subsong0_Start
	dw FeverRemix_Subsong1_Start
	dw FeverRemix_Subsong2_Start
	dw FeverRemix_Subsong3_Start
FeverRemix_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
FeverRemix_ArpeggioTable
FeverRemix_DisarkPointerRegionStart3
FeverRemix_DisarkPointerRegionEnd3

; Declares all the Pitches.
FeverRemix_PitchTable
FeverRemix_DisarkPointerRegionStart4
FeverRemix_DisarkPointerRegionEnd4

; Declares all the Instruments.
FeverRemix_InstrumentTable
FeverRemix_DisarkPointerRegionStart5
	dw FeverRemix_EmptyInstrument
	dw FeverRemix_Instrument1
	dw FeverRemix_Instrument2
	dw FeverRemix_Instrument3
	dw FeverRemix_Instrument4
	dw FeverRemix_Instrument5
	dw FeverRemix_Instrument6
	dw FeverRemix_Instrument7
FeverRemix_DisarkPointerRegionEnd5

FeverRemix_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
FeverRemix_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

FeverRemix_Instrument1
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

FeverRemix_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

FeverRemix_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

FeverRemix_Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	dw -10	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	dw -30	; Pitch.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 80	; No Soft no Hard. Volume: 10. Noise? false.

	db 208	; No Soft no Hard. Volume: 10. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 176	; No Soft no Hard. Volume: 6. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 160	; No Soft no Hard. Volume: 4. Noise? true.
	db 1	; Noise: 1.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

FeverRemix_Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 150	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 300	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 400	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 500	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 600	; Pitch.

	db 6	; Loop to silence.

FeverRemix_Instrument6
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 217	; Soft only. Volume: 11. Volume only.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 209	; Soft only. Volume: 10. Volume only.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 193	; Soft only. Volume: 8. Volume only.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 185	; Soft only. Volume: 7. Volume only.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 169	; Soft only. Volume: 5. Volume only.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 161	; Soft only. Volume: 4. Volume only.

	db 25	; Soft only. Volume: 3.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 25	; Soft only. Volume: 3.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 145	; Soft only. Volume: 2. Volume only.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 9	; Soft only. Volume: 1.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

FeverRemix_Instrument7
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 249	; Soft only. Volume: 15. Volume only.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
FeverRemix_EffectBlockTable
FeverRemix_DisarkPointerRegionStart6
	dw FeverRemix_EffectBlock_P4P0	; Index 0
	dw FeverRemix_EffectBlock_P4P2	; Index 1
	dw FeverRemix_EffectBlock_P4P1	; Index 2
FeverRemix_DisarkPointerRegionEnd6

FeverRemix_EffectBlock_P4P0
	db 4, 0
FeverRemix_EffectBlock_P4P1
	db 4, 1
FeverRemix_EffectBlock_P4P2
	db 4, 2

FeverRemix_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
FeverRemix_Subsong0_DisarkByteRegionStart0
FeverRemix_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 19	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 27	; Base note index (>=0).

FeverRemix_Subsong0_Linker
FeverRemix_Subsong0_DisarkPointerRegionStart1
; Position 0
FeverRemix_Subsong0_Linker_Loop
	dw FeverRemix_Subsong0_Track0
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock0

; Position 1
	dw FeverRemix_Subsong0_Track2
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 2
	dw FeverRemix_Subsong0_Track3
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 3
	dw FeverRemix_Subsong0_Track4
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 4
	dw FeverRemix_Subsong0_Track5
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 5
	dw FeverRemix_Subsong0_Track6
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 6
	dw FeverRemix_Subsong0_Track7
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 7
	dw FeverRemix_Subsong0_Track8
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 8
	dw FeverRemix_Subsong0_Track9
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 9
	dw FeverRemix_Subsong0_Track9
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 10
	dw FeverRemix_Subsong0_Track10
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 11
	dw FeverRemix_Subsong0_Track11
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 12
	dw FeverRemix_Subsong0_Track12
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 13
	dw FeverRemix_Subsong0_Track3
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 14
	dw FeverRemix_Subsong0_Track4
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 15
	dw FeverRemix_Subsong0_Track5
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 16
	dw FeverRemix_Subsong0_Track13
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 17
	dw FeverRemix_Subsong0_Track14
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 18
	dw FeverRemix_Subsong0_Track15
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

; Position 19
	dw FeverRemix_Subsong0_Track16
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_Track1
	dw FeverRemix_Subsong0_LinkerBlock1

FeverRemix_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
FeverRemix_Subsong0_DisarkWordForceReference2
	dw FeverRemix_Subsong0_Linker_Loop

FeverRemix_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
FeverRemix_Subsong0_DisarkWordForceReference3
	dw FeverRemix_Subsong0_SpeedTrack0	; SpeedTrack address.
FeverRemix_Subsong0_DisarkWordForceReference4
	dw FeverRemix_Subsong0_EventTrack0	; EventTrack address.
FeverRemix_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
FeverRemix_Subsong0_DisarkWordForceReference5
	dw FeverRemix_Subsong0_SpeedTrack1	; SpeedTrack address.
FeverRemix_Subsong0_DisarkWordForceReference6
	dw FeverRemix_Subsong0_EventTrack0	; EventTrack address.

FeverRemix_Subsong0_Track0
	db 196
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 132
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 16
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 16
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 11
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track1
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track2
	db 132
	db 2	; New Instrument (2).
	db 32
	db 35
	db 28
	db 8
	db 37
	db 35
	db 32
	db 9
	db 33
	db 37
	db 40
	db 10
	db 40
	db 11
	db 33
	db 4
	db 32
	db 35
	db 32
	db 8
	db 35
	db 32
	db 28
	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 12
	db 8
	db 4
	db 4
	db 32
	db 35
	db 28
	db 8
	db 37
	db 35
	db 32
	db 9
	db 33
	db 37
	db 40
	db 10
	db 40
	db 11
	db 33
	db 16
	db 16
	db 16
	db 60	; Waits for 1 line.

	db 18
	db 18
	db 18
	db 60	; Waits for 1 line.

	db 19
	db 19
	db 19
	db 149
	db 4	; New Instrument (4).
	db 148
	db 2	; New Instrument (2).
	db 20
	db 20
	db 149
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track3
	db 132
	db 2	; New Instrument (2).
	db 32
	db 35
	db 28
	db 8
	db 37
	db 35
	db 32
	db 9
	db 33
	db 37
	db 40
	db 10
	db 40
	db 11
	db 33
	db 4
	db 32
	db 35
	db 32
	db 8
	db 35
	db 32
	db 28
	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 149
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 132
	db 2	; New Instrument (2).
	db 32
	db 35
	db 28
	db 8
	db 37
	db 35
	db 32
	db 9
	db 33
	db 37
	db 40
	db 10
	db 40
	db 11
	db 33
	db 47
	db 45
	db 41
	db 39
	db 60	; Waits for 1 line.

	db 40
	db 43
	db 39
	db 36
	db 38
	db 35
	db 31
	db 33
	db 31
	db 27
	db 25
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track4
	db 137
	db 2	; New Instrument (2).
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 38
	db 42
	db 45
	db 15
	db 45
	db 16
	db 38
	db 9
	db 37
	db 40
	db 37
	db 13
	db 40
	db 37
	db 33
	db 14
	db 26
	db 33
	db 38
	db 15
	db 38
	db 16
	db 30
	db 9
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 38
	db 42
	db 45
	db 13
	db 45
	db 42
	db 38
	db 11
	db 35
	db 39
	db 35
	db 18
	db 39
	db 11
	db 42
	db 16
	db 35
	db 14
	db 42
	db 13
	db 38
	db 11
	db 35
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track5
	db 137
	db 2	; New Instrument (2).
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 25
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 37
	db 40
	db 33
	db 16
	db 42
	db 40
	db 37
	db 14
	db 38
	db 13
	db 33
	db 12
	db 42
	db 11
	db 40
	db 4
	db 35
	db 39
	db 42
	db 16
	db 35
	db 38
	db 42
	db 9
	db 44
	db 4
	db 41
	db 6
	db 38
	db 8
	db 35
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track6
	db 149
	db 2	; New Instrument (2).
	db 37
	db 33
	db 27
	db 16
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 20
	db 35
	db 32
	db 27
	db 13
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 18
	db 33
	db 30
	db 24
	db 13
	db 60	; Waits for 1 line.

	db 18
	db 30
	db 16
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 21
	db 28
	db 25
	db 60	; Waits for 1 line.

	db 26
	db 42
	db 38
	db 32
	db 21
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 25
	db 40
	db 37
	db 32
	db 18
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 23
	db 38
	db 35
	db 29
	db 23
	db 60	; Waits for 1 line.

	db 25
	db 35
	db 26
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 28
	db 38
	db 20
	db 35
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track7
	db 149
	db 2	; New Instrument (2).
	db 37
	db 33
	db 27
	db 16
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 20
	db 35
	db 32
	db 27
	db 13
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 18
	db 33
	db 30
	db 24
	db 13
	db 60	; Waits for 1 line.

	db 18
	db 30
	db 16
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 21
	db 28
	db 25
	db 60	; Waits for 1 line.

	db 26
	db 42
	db 38
	db 32
	db 21
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 25
	db 40
	db 37
	db 32
	db 18
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 23
	db 38
	db 35
	db 29
	db 23
	db 60	; Waits for 1 line.

	db 25
	db 35
	db 26
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 219
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 220
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 38
	db 20
	db 35
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track8
	db 137
	db 2	; New Instrument (2).
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 37
	db 40
	db 33
	db 16
	db 42
	db 40
	db 37
	db 14
	db 38
	db 13
	db 33
	db 12
	db 42
	db 11
	db 40
	db 4
	db 35
	db 39
	db 42
	db 16
	db 35
	db 38
	db 42
	db 9
	db 40
	db 4
	db 40
	db 9
	db 50
	db 44
	db 37
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track9
	db 137
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 15
	db 149
	db 4	; New Instrument (4).
	db 144
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 15
	db 149
	db 4	; New Instrument (4).
	db 144
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 15
	db 149
	db 4	; New Instrument (4).
	db 144
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 18
	db 149
	db 4	; New Instrument (4).
	db 145
	db 2	; New Instrument (2).
	db 149
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track10
	db 144
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 15
	db 61, 12	; Waits for 13 lines.

	db 16
	db 60	; Waits for 1 line.

	db 15
	db 61, 12	; Waits for 13 lines.

	db 16
	db 60	; Waits for 1 line.

	db 15
	db 61, 10	; Waits for 11 lines.

	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 85
	db 2	; Index to an effect block.
	db 209
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track11
	db 132
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 2
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 1
	db 49
	db 32
	db 49
	db 44
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 31
	db 55
	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 32
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 37
	db 24
	db 7
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 21
	db 21
	db 21
	db 21
	db 21
	db 21
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 0	; Index to an effect block.
	db 21
	db 21
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track12
	db 196
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 32
	db 35
	db 28
	db 8
	db 37
	db 35
	db 32
	db 9
	db 33
	db 37
	db 40
	db 10
	db 40
	db 11
	db 33
	db 4
	db 32
	db 35
	db 32
	db 8
	db 35
	db 32
	db 28
	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 12
	db 8
	db 4
	db 4
	db 32
	db 35
	db 28
	db 8
	db 37
	db 35
	db 32
	db 9
	db 33
	db 37
	db 40
	db 10
	db 40
	db 11
	db 33
	db 16
	db 16
	db 16
	db 60	; Waits for 1 line.

	db 18
	db 18
	db 18
	db 60	; Waits for 1 line.

	db 19
	db 19
	db 19
	db 149
	db 4	; New Instrument (4).
	db 148
	db 2	; New Instrument (2).
	db 20
	db 20
	db 149
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track13
	db 137
	db 2	; New Instrument (2).
	db 37
	db 33
	db 27
	db 4
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 8
	db 35
	db 32
	db 27
	db 1
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 6
	db 33
	db 30
	db 24
	db 1
	db 60	; Waits for 1 line.

	db 6
	db 30
	db 4
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 9
	db 28
	db 13
	db 60	; Waits for 1 line.

	db 14
	db 42
	db 38
	db 32
	db 9
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 13
	db 40
	db 37
	db 32
	db 6
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 11
	db 38
	db 35
	db 29
	db 11
	db 60	; Waits for 1 line.

	db 13
	db 35
	db 14
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 16
	db 38
	db 8
	db 35
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track14
	db 137
	db 2	; New Instrument (2).
	db 37
	db 33
	db 27
	db 4
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 8
	db 35
	db 32
	db 27
	db 1
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 6
	db 33
	db 30
	db 24
	db 1
	db 60	; Waits for 1 line.

	db 6
	db 30
	db 4
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 9
	db 28
	db 13
	db 60	; Waits for 1 line.

	db 14
	db 42
	db 38
	db 32
	db 9
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 13
	db 40
	db 37
	db 32
	db 6
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 11
	db 38
	db 35
	db 29
	db 11
	db 60	; Waits for 1 line.

	db 13
	db 35
	db 14
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 207
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 213
	db 4	; New Instrument (4).
	db 2	; Index to an effect block.
	db 208
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 38
	db 8
	db 35
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track15
	db 137
	db 2	; New Instrument (2).
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 3
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 37
	db 40
	db 33
	db 16
	db 42
	db 40
	db 37
	db 14
	db 38
	db 13
	db 33
	db 12
	db 42
	db 11
	db 40
	db 4
	db 35
	db 39
	db 42
	db 16
	db 35
	db 38
	db 42
	db 9
	db 44
	db 4
	db 41
	db 6
	db 38
	db 8
	db 35
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong0_Track16
	db 137
	db 2	; New Instrument (2).
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 149
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 137
	db 2	; New Instrument (2).
	db 37
	db 40
	db 33
	db 13
	db 42
	db 40
	db 37
	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 149
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 144
	db 2	; New Instrument (2).
	db 37
	db 40
	db 33
	db 37
	db 42
	db 40
	db 37
	db 14
	db 38
	db 42
	db 33
	db 38
	db 42
	db 37
	db 40
	db 42
	db 45
	db 45
	db 42
	db 45
	db 47
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 196
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 213
	db 3	; New Instrument (3).
	db 1	; Index to an effect block.
	db 201
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


; The speed tracks
FeverRemix_Subsong0_SpeedTrack0
	db 14	; Value: 7.
	db 253	; Wait for 127 lines.
FeverRemix_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
FeverRemix_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

FeverRemix_Subsong0_DisarkByteRegionEnd0
; Subsong 1
; ----------------------
FeverRemix_Subsong1_DisarkByteRegionStart0
FeverRemix_Subsong1_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 1	; Loop start index (>=0).
	db 1	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 0	; Base note index (>=0).

FeverRemix_Subsong1_Linker
FeverRemix_Subsong1_DisarkPointerRegionStart1
; Position 0
	dw FeverRemix_Subsong1_Track0
	dw FeverRemix_Subsong1_Track1
	dw FeverRemix_Subsong1_Track1
	dw FeverRemix_Subsong1_LinkerBlock0

; Position 1
FeverRemix_Subsong1_Linker_Loop
	dw FeverRemix_Subsong1_Track1
	dw FeverRemix_Subsong1_Track1
	dw FeverRemix_Subsong1_Track1
	dw FeverRemix_Subsong1_LinkerBlock1

FeverRemix_Subsong1_DisarkPointerRegionEnd1
	dw 0	; Loop.
FeverRemix_Subsong1_DisarkWordForceReference2
	dw FeverRemix_Subsong1_Linker_Loop

FeverRemix_Subsong1_LinkerBlock0
	db 9	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
FeverRemix_Subsong1_DisarkWordForceReference3
	dw FeverRemix_Subsong1_SpeedTrack0	; SpeedTrack address.
FeverRemix_Subsong1_DisarkWordForceReference4
	dw FeverRemix_Subsong1_EventTrack0	; EventTrack address.
FeverRemix_Subsong1_LinkerBlock1
	db 1	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
FeverRemix_Subsong1_DisarkWordForceReference5
	dw FeverRemix_Subsong1_SpeedTrack0	; SpeedTrack address.
FeverRemix_Subsong1_DisarkWordForceReference6
	dw FeverRemix_Subsong1_EventTrack0	; EventTrack address.

FeverRemix_Subsong1_Track0
	db 175
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 44
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong1_Track1
	db 61, 127	; Waits for 128 lines.


; The speed tracks
FeverRemix_Subsong1_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
FeverRemix_Subsong1_EventTrack0
	db 255	; Wait for 128 lines.

FeverRemix_Subsong1_DisarkByteRegionEnd0
; Subsong 2
; ----------------------
FeverRemix_Subsong2_DisarkByteRegionStart0
FeverRemix_Subsong2_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 1	; Loop start index (>=0).
	db 1	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 7	; Base note index (>=0).

FeverRemix_Subsong2_Linker
FeverRemix_Subsong2_DisarkPointerRegionStart1
; Position 0
	dw FeverRemix_Subsong2_Track0
	dw FeverRemix_Subsong2_Track1
	dw FeverRemix_Subsong2_Track1
	dw FeverRemix_Subsong2_LinkerBlock0

; Position 1
FeverRemix_Subsong2_Linker_Loop
	dw FeverRemix_Subsong2_Track1
	dw FeverRemix_Subsong2_Track1
	dw FeverRemix_Subsong2_Track1
	dw FeverRemix_Subsong2_LinkerBlock1

FeverRemix_Subsong2_DisarkPointerRegionEnd1
	dw 0	; Loop.
FeverRemix_Subsong2_DisarkWordForceReference2
	dw FeverRemix_Subsong2_Linker_Loop

FeverRemix_Subsong2_LinkerBlock0
	db 19	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
FeverRemix_Subsong2_DisarkWordForceReference3
	dw FeverRemix_Subsong2_SpeedTrack0	; SpeedTrack address.
FeverRemix_Subsong2_DisarkWordForceReference4
	dw FeverRemix_Subsong2_EventTrack0	; EventTrack address.
FeverRemix_Subsong2_LinkerBlock1
	db 1	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
FeverRemix_Subsong2_DisarkWordForceReference5
	dw FeverRemix_Subsong2_SpeedTrack0	; SpeedTrack address.
FeverRemix_Subsong2_DisarkWordForceReference6
	dw FeverRemix_Subsong2_EventTrack0	; EventTrack address.

FeverRemix_Subsong2_Track0
	db 174
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 55
	db 61, 127	; Waits for 128 lines.


FeverRemix_Subsong2_Track1
	db 61, 127	; Waits for 128 lines.


; The speed tracks
FeverRemix_Subsong2_SpeedTrack0
	db 10	; Value: 5.
	db 253	; Wait for 127 lines.

; The event tracks
FeverRemix_Subsong2_EventTrack0
	db 255	; Wait for 128 lines.

FeverRemix_Subsong2_DisarkByteRegionEnd0
; Subsong 3
; ----------------------
FeverRemix_Subsong3_DisarkByteRegionStart0
FeverRemix_Subsong3_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 0	; Base note index (>=0).

FeverRemix_Subsong3_Linker
FeverRemix_Subsong3_DisarkPointerRegionStart1
; Position 0
FeverRemix_Subsong3_Linker_Loop
	dw FeverRemix_Subsong3_Track0
	dw FeverRemix_Subsong3_Track0
	dw FeverRemix_Subsong3_Track0
	dw FeverRemix_Subsong3_LinkerBlock0

FeverRemix_Subsong3_DisarkPointerRegionEnd1
	dw 0	; Loop.
FeverRemix_Subsong3_DisarkWordForceReference2
	dw FeverRemix_Subsong3_Linker_Loop

FeverRemix_Subsong3_LinkerBlock0
	db 1	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
FeverRemix_Subsong3_DisarkWordForceReference3
	dw FeverRemix_Subsong3_SpeedTrack0	; SpeedTrack address.
FeverRemix_Subsong3_DisarkWordForceReference4
	dw FeverRemix_Subsong3_EventTrack0	; EventTrack address.

FeverRemix_Subsong3_Track0
	db 61, 127	; Waits for 128 lines.


; The speed tracks
FeverRemix_Subsong3_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
FeverRemix_Subsong3_EventTrack0
	db 255	; Wait for 128 lines.

FeverRemix_Subsong3_DisarkByteRegionEnd0
