; Sound Effects for song fx, version 2.0, generated by Arkos Tracker 2.

fx_SoundEffects
fx_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
fx_SoundEffectsDisarkPointerRegionStart0
	dw 0	; Sound effect 1.
	dw 0	; Sound effect 2.
	dw 0	; Sound effect 3.
	dw 0	; Sound effect 4.
	dw 0	; Sound effect 5.
	dw 0	; Sound effect 6.
	dw 0	; Sound effect 7.
	dw 0	; Sound effect 8.
	dw fx_SoundEffects_Sound9	; Sound effect 9.
	dw 0	; Sound effect 10.
	dw 0	; Sound effect 11.
	dw 0	; Sound effect 12.
	dw 0	; Sound effect 13.
	dw fx_SoundEffects_Sound14	; Sound effect 14.
	dw fx_SoundEffects_Sound15	; Sound effect 15.
	dw fx_SoundEffects_Sound16	; Sound effect 16.
	dw 0	; Sound effect 17.
fx_SoundEffectsDisarkPointerRegionEnd0

fx_SoundEffectsDisarkByteRegionStart1
; Sound effect 9.
fx_SoundEffects_Sound9
	db 0	; Speed

fx_SoundEffects_Sound9_Loop	db 61	; Soft only. Volume: 15.
	dw 95	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 106	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 119	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 134	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 150	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 169	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 190	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 169	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 150	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 134	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 119	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 106	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 95	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 60	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 53	; Software period.

	db 5	; Soft only. Volume: 1.
	dw 47	; Software period.

	db 4	; End of the sound effect.

; Sound effect 14.
fx_SoundEffects_Sound14
	db 0	; Speed

fx_SoundEffects_Sound14_Loop	db 248	; No soft, no hard. Volume: 15.
	db 18	; Noise: 18.

	db 248	; No soft, no hard. Volume: 15.
	db 20	; Noise: 20.

	db 200	; No soft, no hard. Volume: 9.
	db 21	; Noise: 21.

	db 184	; No soft, no hard. Volume: 7.
	db 21	; Noise: 21.

	db 176	; No soft, no hard. Volume: 6.
	db 21	; Noise: 21.

	db 4	; End of the sound effect.

; Sound effect 15.
fx_SoundEffects_Sound15
	db 0	; Speed

fx_SoundEffects_Sound15_Loop	db 61	; Soft only. Volume: 15.
	dw 268	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 253	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 239	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 225	; Software period.

	db 4	; End of the sound effect.

; Sound effect 16.
fx_SoundEffects_Sound16
	db 0	; Speed

fx_SoundEffects_Sound16_Loop	db 232	; No soft, no hard. Volume: 13.
	db 1	; Noise: 1.

	db 208	; No soft, no hard. Volume: 10.
	db 1	; Noise: 1.

	db 200	; No soft, no hard. Volume: 9.
	db 1	; Noise: 1.

	db 184	; No soft, no hard. Volume: 7.
	db 1	; Noise: 1.

	db 168	; No soft, no hard. Volume: 5.
	db 1	; Noise: 1.

	db 160	; No soft, no hard. Volume: 4.
	db 1	; Noise: 1.

	db 144	; No soft, no hard. Volume: 2.
	db 1	; Noise: 1.

	db 136	; No soft, no hard. Volume: 1.
	db 1	; Noise: 1.

	db 4	; End of the sound effect.

fx_SoundEffectsDisarkByteRegionEnd1
